# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fanghaizhou/project/crypto_pre

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fanghaizhou/project/crypto_pre/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fanghaizhou/project/crypto_pre/build/CMakeFiles /home/fanghaizhou/project/crypto_pre/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fanghaizhou/project/crypto_pre/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

common/df_alg.o: common/df_alg.cc.o
.PHONY : common/df_alg.o

# target to build an object file
common/df_alg.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/df_alg.cc.o
.PHONY : common/df_alg.cc.o

common/df_alg.i: common/df_alg.cc.i
.PHONY : common/df_alg.i

# target to preprocess a source file
common/df_alg.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/df_alg.cc.i
.PHONY : common/df_alg.cc.i

common/df_alg.s: common/df_alg.cc.s
.PHONY : common/df_alg.s

# target to generate assembly for a file
common/df_alg.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/df_alg.cc.s
.PHONY : common/df_alg.cc.s

common/parquet_io.o: common/parquet_io.cc.o
.PHONY : common/parquet_io.o

# target to build an object file
common/parquet_io.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/parquet_io.cc.o
.PHONY : common/parquet_io.cc.o

common/parquet_io.i: common/parquet_io.cc.i
.PHONY : common/parquet_io.i

# target to preprocess a source file
common/parquet_io.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/parquet_io.cc.i
.PHONY : common/parquet_io.cc.i

common/parquet_io.s: common/parquet_io.cc.s
.PHONY : common/parquet_io.s

# target to generate assembly for a file
common/parquet_io.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/parquet_io.cc.s
.PHONY : common/parquet_io.cc.s

common/time_utils.o: common/time_utils.cc.o
.PHONY : common/time_utils.o

# target to build an object file
common/time_utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/time_utils.cc.o
.PHONY : common/time_utils.cc.o

common/time_utils.i: common/time_utils.cc.i
.PHONY : common/time_utils.i

# target to preprocess a source file
common/time_utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/time_utils.cc.i
.PHONY : common/time_utils.cc.i

common/time_utils.s: common/time_utils.cc.s
.PHONY : common/time_utils.s

# target to generate assembly for a file
common/time_utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/time_utils.cc.s
.PHONY : common/time_utils.cc.s

common/utils.o: common/utils.cc.o
.PHONY : common/utils.o

# target to build an object file
common/utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/utils.cc.o
.PHONY : common/utils.cc.o

common/utils.i: common/utils.cc.i
.PHONY : common/utils.i

# target to preprocess a source file
common/utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/utils.cc.i
.PHONY : common/utils.cc.i

common/utils.s: common/utils.cc.s
.PHONY : common/utils.s

# target to generate assembly for a file
common/utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/common/utils.cc.s
.PHONY : common/utils.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/main.cc.s
.PHONY : main.cc.s

websocket_client.o: websocket_client.cc.o
.PHONY : websocket_client.o

# target to build an object file
websocket_client.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/websocket_client.cc.o
.PHONY : websocket_client.cc.o

websocket_client.i: websocket_client.cc.i
.PHONY : websocket_client.i

# target to preprocess a source file
websocket_client.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/websocket_client.cc.i
.PHONY : websocket_client.cc.i

websocket_client.s: websocket_client.cc.s
.PHONY : websocket_client.s

# target to generate assembly for a file
websocket_client.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/websocket_client.cc.s
.PHONY : websocket_client.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... common/df_alg.o"
	@echo "... common/df_alg.i"
	@echo "... common/df_alg.s"
	@echo "... common/parquet_io.o"
	@echo "... common/parquet_io.i"
	@echo "... common/parquet_io.s"
	@echo "... common/time_utils.o"
	@echo "... common/time_utils.i"
	@echo "... common/time_utils.s"
	@echo "... common/utils.o"
	@echo "... common/utils.i"
	@echo "... common/utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... websocket_client.o"
	@echo "... websocket_client.i"
	@echo "... websocket_client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

